Traceback (most recent call last):
  File "/Users/mike/opt/anaconda3/envs/cs185c/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mike/opt/anaconda3/envs/cs185c/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/cs185c/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/cs185c/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mike/opt/anaconda3/envs/cs185c/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/mike/opt/anaconda3/envs/cs185c/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mike/opt/anaconda3/envs/cs185c/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
grid = np.fromfile(os.path.join(run_dir,'TS_surf_daily_mean',
                                'TS_surf_daily_mean.0000068256.data'), '>f4')
grid = grid.reshape((2,nrows,ncols))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 3[0m
[1;32m      1[0m grid [38;5;241m=[39m np[38;5;241m.[39mfromfile(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(run_dir,[38;5;124m'[39m[38;5;124mTS_surf_daily_mean[39m[38;5;124m'[39m,
[1;32m      2[0m                                 [38;5;124m'[39m[38;5;124mTS_surf_daily_mean.0000068256.data[39m[38;5;124m'[39m), [38;5;124m'[39m[38;5;124m>f4[39m[38;5;124m'[39m)
[0;32m----> 3[0m grid [38;5;241m=[39m grid[38;5;241m.[39mreshape(([38;5;241m2[39m,[43mnrows[49m,ncols))

[0;31mNameError[0m: name 'nrows' is not defined

